### ISSUE TITLE
NOT HACKTOBER ACCEPTED

### ISSUE THREAD

**Issue by Tushar7890** [TwoGenius/HacktoberFest2022#17]
Heyy @Naman-pokhriyal i merged my blog page in your repo but on hacktober website  it is showing that this repo is not participating 
does it is to be counted as hacktober accepted or not ?
@Naman-pokhriyal

**Comment by JatinBisht2308** [comment]
You can star the repo and then raise pr, without hac-accepted it wont count

**Comment by Tushar7890** [comment]
> You can star the repo and then raise pr, without hac-accepted it wont count

I created PR and repo owner merged my PR but does not  give me  a label "Hacktober-Accepted"

**Comment by JatinBisht2308** [comment]
Raise another pr brother we will see it okeh
