### ISSUE TITLE
want to add my portfolio website here

### ISSUE THREAD

**Issue by aksharma27** [TwoGenius/HacktoberFest2022#24]

**Comment by Sandyy07** [comment]
Hi , Kindly please assign this issue to me .

**Comment by JatinBisht2308** [comment]
You have to create the portfolio of yours and then follow the readme

**Comment by yosaami** [comment]
assign me this project, please.

**Comment by JatinBisht2308** [comment]
please read readme then raise issue.

**Comment by aksharma27** [comment]
> assign me this project, please.

This repo is expelled from hacktoberfest.
